name: NavigatorVMS Local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    enabled: true
    type: default
  - key: tenantSubdomain
    value: demo
    enabled: true
    type: default
  - key: tenantToken
    value: ''
    enabled: true
    type: secret
  - key: platformToken
    value: ''
    enabled: true
    type: secret
  - key: assetId
    value: ''
    enabled: true
    type: default
  - key: allocationId
    value: ''
    enabled: true
    type: default
  - key: locationId
    value: ''
    enabled: true
    type: default
  - key: userId
    value: ''
    enabled: true
    type: default
  - key: driverId
    value: ''
    enabled: true
    type: default
  - key: insuranceId
    value: ''
    enabled: true
    type: default
  - key: supplierId
    value: ''
    enabled: true
    type: default
  - key: fuelLogId
    value: ''
    enabled: true
    type: default
  - key: maintenanceId
    value: ''
    enabled: true
    type: default
  - key: notificationId
    value: ''
    enabled: true
    type: default
  - key: reportJobId
    value: ''
    enabled: true
    type: default
